### PR TITLE
Fixes 'google-services.json is missing' error

### LINKED ISSUE #3: File google-services.json is missing from module root folder.
Following the instructions listed in the README as well as on [Android's tutorial](https://developers.google.com/cloud-messaging/android/client) I'm still getting the error below:
```
File google-services.json is missing from module root folder. The Google Services Plugin cannot function without it.
```

I put the google-services.json in the `android/app` directory. Have you seen this error?

### PR DESCRIPTION
**Pull request by lukefanning**
Resolves #3

### CODE REVIEW

**Comment by oney** [comment]
Thanks!
I can't reproduce the issue, but the app still works after removing `apply plugin: 'com.google.gms.google-services'` from `android/build.gradle`. So, I think removing it will help some people prevent facing this issue.

I don't want to remove `react-native-system-notification` dependency from this module, because I plan to use this module to create notifications. It more focuses on creating notification, and `react-native-gcm-android` focuses on GCM. Although it has some issue so I don't use it, let it stay here now.

Can you add a commit not to remove `react-native-system-notification` in this PR? And I will merge it.

**Comment by lukefanning** [comment]
Yeah I was thinking about how our app would generate notifications while its not running and doing it via the background service in your module would be great :). Restored the dependency.

**Comment by oney** [comment]
Currently this module support to create notification when the app is not running(closed).
See [this](https://github.com/oney/react-native-gcm-android#the-app-is-killedclosed)
When the app is closed and receive GCM notification, it will create [BackgroundService](https://github.com/oney/react-native-gcm-android/blob/master/android/src/main/java/com/oney/gcm/BackgroundService.java) to launch a React Native instance to handle notification. After finishing, BackgroundService will be destroyed.

**Comment by fender** [comment]
@oney Can you create a new release for NPM after the commit 8 days ago? ^

**Comment by oney** [comment]
@fender No problem. Done in 0.1.6

**Pull request merged**
